version: '3.8'

services:
  orchestrator:
    container_name: orchestrator
    restart: always
    build: ./orchestrator
    #image: ivanskv2000/mlops-server
    volumes:
      - ./orchestrator/:/app
      - ./ml_models/:/ml_models
      - ./executions:/executions
    ports:
      - 8000:8000
    depends_on:
      - nlp_nl2ml
    #env_file:
    #  - ./.env
    expose:
      - "8000"
  nlp_nl2ml:
    container_name: nlp_nl2ml
    restart: always
    build: ./ml_models/nlp_nl2ml
    #image: postgres:10
    volumes:
      - ./ml_models/nlp_nl2ml/:/model
      - ./executions:/executions
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5430:5430"
    expose:
      - "5430"
    #env_file:
    #  - .env