version: '3.8'

services:
  orchestrator:
    container_name: orchestrator
    restart: always
    build: ./orchestrator
    volumes:
      - ./orchestrator/:/app
      - ./${MODELS_DIR}/:/ml_models
      - ./${EXEC_DIR}:/executions
    environment:
      - PORT=${ORCHESTRATOR_PORT}
    ports:
      - ${ORCHESTRATOR_PORT}:${ORCHESTRATOR_PORT}
    depends_on:
      - nlp_nl2ml
      - nlp_sentiment_tfidf_lr
    #env_file:
    #  - ./.env
    expose:
      - ${ORCHESTRATOR_PORT}
  nlp_nl2ml:
    container_name: nlp_nl2ml
    restart: always
    build: ./${MODELS_DIR}/nlp_nl2ml
    volumes:
      - ./${MODELS_DIR}/nlp_nl2ml/:/model
      - ./${EXEC_DIR}:/executions
    environment:
      - EXEC_DIR=${EXEC_DIR}
    ports:
      - "5430"
    expose:
      - "5430"
    #env_file:
    #  - .env
  nlp_sentiment_tfidf_lr:
    container_name: nlp_sentiment_tfidf_lr
    restart: always
    build: ./${MODELS_DIR}/nlp_sentiment_tfidf_lr
    volumes:
      - ./${MODELS_DIR}/nlp_sentiment_tfidf_lr/:/model
      - ./${EXEC_DIR}:/executions
    environment:
      - EXEC_DIR=${EXEC_DIR}
    ports:
      - "5430"
    expose:
      - "5430"
    #env_file:
    #  - .env