version: '3.8'

services:
  server:
    container_name: server
    restart: always
    build: ./server
    image: ivanskv2000/mlops-server
    volumes:
      - ./server/:/app
    ports:
      - 8000:5000
    depends_on:
      - database
    env_file:
      - ./.env
  database:
    container_name: database
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    expose:
      - "5435"
    env_file:
      - .env