---
# ML Model Configuration & Metadata

name: NL2ML
tech_name: nlp-nl2ml
description: Natural Language to Machine Learning (NL2ML) Model

task_type: classification
task_class: multi-class

data_type: string
has_explanation: True