---
# ML Model Configuration & Metadata

name: Sentiment Classification Model
tech_name: nlp_sentiment_tfidf_lr
description: TBC

task_type: classification
task_class: one-class

data_type: string
has_explanation: True